### ISSUE TITLE
Permission to re-use some documentation in new internals documention

### ISSUE THREAD

**Issue by gchp** [nrc/stupid-stats#3]
Hey @nrc!

I've been (slowly) working through some internals documentation, and was pointed to this repo for information on `CompilerCalls`. While I was reading your guide, I noticed the section on the overview of the different phases in compilation. It's probably the best overview of the process I've come across, and I was wondering if you would be ok with me re-using the information you give here on the various phases in the internals docs?

I have a version of the ["Overview" section on my rust fork](https://github.com/gchp/rust/blob/internals/src/doc/internals/overview.md), so you can see exactly what I've re-used. I won't submit it without your permission, though, so let me know if you are ok with me doing so.

Aside from that overview section, I've been documenting some of the other areas of the driver, and found this guide very helpful, so thanks for that!

**Comment by nrc** [comment]
Hi @gchp, that's totally fine, thanks for checking.

**Comment by gchp** [comment]
That's great, thank you!
